import subprocess

the_code = '.\\tests.py'

deeppavlov_ = ...
flair_ = ...
nltk_ = ...
pattern_ = 'E:\\venv\\hazard_pattern\\python.exe'
pycorenlp_ = ...
sister_ = ...
spacy_ = ...
textblob_ = ...
use_ = ...



# res = subprocess.call([pattern_, the_code])

from configuration import SentimentConfig

sc = SentimentConfig()
sc.lib_env = pattern_
sc.the_code = the_code

sc.call_it()
